spiffe-oidc-discovery-provider:
  enabled: true
  namespaceOverride: spire-server
  tls:
    spire:
      enabled: false

spire-server:
  namespaceOverride: spire-server
  nodeAttestor:
    k8sPSAT:
      serviceAccountAllowList: ["spire-system:spire-agent"]
  notifier:
    k8sBundle:
      namespace: spire-system

spiffe-csi-driver:
  enabled: true
  namespaceOverride: spire-system

spire-agent:
  enabled: true
  namespaceOverride: spire-system
  serviceAccount:
    # -- The name of the service account to use.
    name: spire-agent
  server:
    namespaceOverride: spire-server
