{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spike-nexus.serviceAccountName" . }}
  namespace: {{ include "spike-nexus.namespace" . }}
  labels:
    {{- include "spike-nexus.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
