apiVersion: v1
kind: Pod
metadata:
  name: standalone-cm-client
spec:
  terminationGracePeriodSeconds: 1
  containers:
    - name: client
      image: ghcr.io/spiffe/spire-agent:1.15.3
      command: ["/opt/spire/bin/spire-agent"]
      args: ["api", "watch", "-socketPath", "/spiffe-workload-api/spire-agent.sock"]
      volumeMounts:
        - name: spiffe-workload-api
          mountPath: /spiffe-workload-api
          readOnly: true
  volumes:
    - name: spiffe-workload-api
      csi:
        driver: csi.spiffe.io
        readOnly: true
