kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: ClusterConfiguration
    metadata:
      name: config
    apiServer:
      extraArgs:
        service-account-key-file: /etc/kubernetes/pki/sa.pub
        service-account-signing-key-file: /etc/kubernetes/pki/sa.key
        service-account-issuer: api,spire-agent
        api-audiences: api,spire-server
        # admission-control-config-file: /etc/kubernetes/pki/admctrl/admission-control.yaml
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /var/run/spiffe/socat/unix/k8s-spire-server-a/public
        containerPath: /var/run/spiffe/socat/unix/k8s-spire-server-a/public
      - hostPath: /var/run/spiffe/socat/unix/k8s-spire-server-b/public
        containerPath: /var/run/spiffe/socat/unix/k8s-spire-server-b/public
  - role: worker
    extraMounts:
      - hostPath: /var/run/spiffe/socat/unix/k8s-spire-server-a/public
        containerPath: /var/run/spiffe/socat/unix/k8s-spire-server-a/public
      - hostPath: /var/run/spiffe/socat/unix/k8s-spire-server-b/public
        containerPath: /var/run/spiffe/socat/unix/k8s-spire-server-b/public
      - hostPath: /var/run/spiffe/socat/unix/k8s-spire-agent-2-a/public
        containerPath: /var/run/spiffe/socat/unix/k8s-spire-agent-a/public
      - hostPath: /var/run/spiffe/socat/unix/k8s-spire-agent-2-b/public
        containerPath: /var/run/spiffe/socat/unix/k8s-spire-agent-b/public
  - role: worker
    extraMounts:
      - hostPath: /var/run/spiffe/socat/unix/k8s-spire-server-a/public
        containerPath: /var/run/spiffe/socat/unix/k8s-spire-server-a/public
      - hostPath: /var/run/spiffe/socat/unix/k8s-spire-server-b/public
        containerPath: /var/run/spiffe/socat/unix/k8s-spire-server-b/public
      - hostPath: /var/run/spiffe/socat/unix/k8s-spire-agent-3-a/public
        containerPath: /var/run/spiffe/socat/unix/k8s-spire-agent-a/public
      - hostPath: /var/run/spiffe/socat/unix/k8s-spire-agent-3-b/public
        containerPath: /var/run/spiffe/socat/unix/k8s-spire-agent-b/public
  - role: worker
    extraMounts:
      - hostPath: /var/run/spiffe/socat/unix/k8s-spire-server-a/public
        containerPath: /var/run/spiffe/socat/unix/k8s-spire-server-a/public
      - hostPath: /var/run/spiffe/socat/unix/k8s-spire-server-b/public
        containerPath: /var/run/spiffe/socat/unix/k8s-spire-server-b/public
      - hostPath: /var/run/spiffe/socat/unix/k8s-spire-agent-4-a/public
        containerPath: /var/run/spiffe/socat/unix/k8s-spire-agent-a/public
      - hostPath: /var/run/spiffe/socat/unix/k8s-spire-agent-4-b/public
        containerPath: /var/run/spiffe/socat/unix/k8s-spire-agent-b/public
