apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spiffe-step-ssh.fullname" . }}-certificate-issuer-password
  labels:
    {{- include "spiffe-step-ssh.labels" . | nindent 4 }}
data:
  password: {{ .Values.caPassword | b64enc }}
