apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spiffe-step-ssh.fullname" . }}-secrets
  labels:
    {{- include "spiffe-step-ssh.labels" . | nindent 4 }}
data:
  root_ca_key: {{ .Values.inject.secrets.x509.root_ca_key | b64enc }}
  intermediate_ca_key: {{ .Values.inject.secrets.x509.intermediate_ca_key | b64enc }}
  ssh_host_ca_key: {{ .Values.inject.secrets.ssh.host_ca_key | b64enc }}
  ssh_user_ca_key: {{ .Values.inject.secrets.ssh.user_ca_key | b64enc }}
