{{- $namespace := include "spire-server.namespace" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spire-lib.bundle-configmap" . }}
  namespace: {{ .Values.notifier.k8sbundle.namespace | default $namespace }}
  {{- with .Values.configMap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
