{{- if and .Values.notifier.k8sBundle.enabled .Values.bundlePublisher.k8sConfigMap.enabled }}
{{- fail "You can only enable either notifier.k8sBundle or bundlePublisher.k8sConfigMap." }}
{{- end }}
{{- if .Values.notifier.k8sBundle.enabled }}
{{- $namespace := include "spire-server.bundle-namespace" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spire-lib.bundle-configmap" . }}
  namespace: {{ $namespace }}
  {{- with .Values.configMap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
