{{- $root := . }}
{{- with .Values.controllerManager }}
{{- range $key, $value := .extraCRs.clusterStaticEntries }}
{{-   range $mkey, $mvalue := $value.metadata }}
{{-     if not (has $mkey (list "labels" "annotations")) }}
{{-       fail (printf "Unsupported metadata property specified: %s" $mkey) }}
{{-     end }}
{{-   end }}
{{-   range $skey, $svalue := $value.spec }}
{{-     if not (has $skey (list "admin" "dnsNames" "downstream" "federatesWith" "hint" "jwtSVIDTTL" "parentID" "selectors" "spiffeID" "x509SVIDTTL")) }}
{{-       fail (printf "Unsupported metadata property specified: %s" $skey) }}
{{-     end }}
{{-   end }}
{{-   range $rprop := list "spiffeID" "selectors" "parentID" }}
{{-     if not (hasKey $value.spec $rprop) }}
{{-       fail (printf "Required property %s was not specified" $rprop) }}
{{-     end }}
{{-   end }}
---
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterStaticEntry
metadata:
  {{- if ($value.metadata).name }}
  name: {{ $value.metadata.name }}
  {{- else }}
  name: {{ $root.Release.Namespace }}-{{ include "spire-controller-manager.fullname" $root }}-{{ $key }}
  {{- end }}
  {{- with $value.metadata }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
spec:
  className: {{ include "spire-server.controller-manager-class-name" $root | quote }}
  {{- with $value.spec }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
