{{- $root := . }}
{{- with .Values.upstreamAuthority.ejbca }}
{{- if and (eq (.enabled | toString) "true") (eq (.secret.create | toString) "true") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spire-server.upstream-ejbca-secret" $root }}
  namespace: {{ include "spire-server.namespace" $root }}
  labels:
    {{- include "spire-server.labels" $root | nindent 4 }}
data:
  {{- with .secret.data }}
  client.crt: {{ .clientCert | b64enc }}
  client.key: {{ .clientKey | b64enc }}
  {{- if ne .caCert "" }}
  ca.crt: {{ .caCert | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
