{{- if .Values.global.spire.namespaces.system.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.spire.namespaces.system.name }}
  {{- if .Values.global.spire.namespaces.system.labels }}
  labels:
    {{- .Values.global.spire.namespaces.system.labels | toYaml | nindent 4 }}
  {{- end }}
  {{- if .Values.global.spire.namespaces.system.annotations }}
  annotations:
    {{- .Values.global.spire.namespaces.system.annotations | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
