{{- if .Values.global.spire.namespaces.server.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.spire.namespaces.server.name }}
  {{- if .Values.global.spire.namespaces.server.labels }}
  labels:
    {{- .Values.global.spire.namespaces.server.labels | toYaml | nindent 4 }}
  {{- end }}
  {{- if .Values.global.spire.namespaces.server.annotations }}
  annotations:
    {{- .Values.global.spire.namespaces.server.annotations | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
