spire-server:
  tornjak:
    enabled: true

tornjak-frontend:
  enabled: true
  apiServerURL: "http://localhost:10000"
  service:
    type: ClusterIP
    port: 3000
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 512Mi
