{{- if eq (.Values.global.openshift | toString) "true" }}
{{- $privileged := false }}
{{- $escalates := false }}
{{- $cfgs := list (.Values | toYaml | fromYaml) }}
{{- range $a := (.Values.agents | default dict) }}
{{-   $cfgs = append $cfgs ($a | toYaml | fromYaml) }}
{{- end }}
{{- range $cfg := $cfgs }}
{{-   if or (dig "nodeAttestor" "tpmDirect" "enabled" false $cfg) (dig "securityContext" "privileged" false $cfg) }}
{{-     $privileged = true }}
{{-   end }}
{{-   if dig "securityContext" "allowPrivilegeEscalation" false $cfg }}
{{-     $escalates = true }}
{{-   end }}
{{- end }}
{{- $escalates = or $escalates $privileged }}
{{- $hostPorts := false }}
{{- range $cfg := $cfgs }}
{{-   range $c := concat (dig "initContainers" (list) $cfg) (dig "extraContainers" (list) $cfg) }}
{{-     range $port := (dig "ports" (list) ($c | toYaml | fromYaml)) }}
{{-       if $port.hostPort }}
{{-         $hostPorts = true }}
{{-       end }}
{{-     end }}
{{-   end }}
{{- end }}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: {{ include "spire-agent.fullname" . | quote }}
readOnlyRootFilesystem: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - {{ printf "system:serviceaccount:%s:%s" (include "spire-agent.namespace" .) (include "spire-agent.serviceAccountName" .) | quote }}
volumes:
  - configMap
  - hostPath
  - projected
  - secret
  - emptyDir
allowedCapabilities: null
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: true
allowHostPID: true
allowHostPorts: {{ $hostPorts }}
allowPrivilegeEscalation: {{ $escalates }}
allowPrivilegedContainer: {{ $privileged }}
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups: []
priority: null
requiredDropCapabilities: null

{{ end }}
