apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  shareProcessNamespace: true
  containers:
  - name: nginx
    image: nginx
    command:
    - /bin/sh
    - -c
    - |
      echo $$$$ > $$SPIFFE_HELPER_PID_CERTS
      cat > /etc/nginx/conf.d/ssl.conf <<EOF
      server {
          listen       443 ssl;
          server_name  localhost;
          ssl_certificate     /certs/tls.crt;
          ssl_certificate_key /certs/tls.key;
          location / {
              root   /usr/share/nginx/html;
              index  index.html index.htm;
          }
          error_page   500 502 503 504  /50x.html;
          location = /50x.html {
              root   /usr/share/nginx/html;
          }
      }
      EOF
      exec nginx -g "daemon off;"
    volumeMounts:
    - name: certs
      mountPath: /certs
    ports:
    - containerPort: 443
  volumes:
  - name: certs
    csi:
      driver: helper.spiffe.io
      volumeAttributes:
        renewSignal: SIGHUP
        pidContainer: nginx

        addIntermediatesToBundle: "true"

        svidFileName: tls.crt
        svidKeyFileName: tls.key
        svidBundleFileName: ca.pem
