spire-server:
  federation:
    enabled: true
    ingress:
      enabled: true
      controllerType: ingress-nginx
      annotations:
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"

      # className: nginx
 
      hosts:
        - host: spire-server-federation.example.org
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - spire-server-federation.example.org
