spiffe-oidc-discovery-provider:
  tests:
    tls:
      enabled: true
  ingress:
    enabled: true
    controllerType: ingress-nginx
      
    # className: nginx

    # You must override these in your own values file with the appropriate hostname
    # and secret or it wont start.
    hosts:
      - host: oidc-discovery.example.org
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: tls-cert
        hosts:
          - oidc-discovery.example.org
