spiffe-oidc-discovery-provider:
  tests:
    tls:
      enabled: true
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

      # Optional settings you may put in your own values.
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
      
    # className: nginx

    # You must override these in your own values file with the appropriate hostname
    # and secret or it wont start.
    hosts:
      - host: oidc-discovery.example.org
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: tls-cert
        hosts:
          - oidc-discovery.example.org
