spire-server:
  tests:
    tls:
      enabled: true
  federation:
    enabled: true
    ingress:
      enabled: true
      controllerType: ingress-nginx

      # className: nginx
 
      hosts:
        - host: spire-server-federation.example.org
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - spire-server-federation.example.org
          secretName: spire-server-federation-tls
