global:
  openshift: false
  spire:
    recommendations:
      enabled: true
    namespaces:
      create: false
    ingressControllerType: ingress-nginx
    clusterName: b
    trustDomain: b-org.local
    bundleConfigMap: spire-bundle-b
    caSubject:
      country: US
      organization: B
      commonName: b.local

spire-server:
  federation:
    enabled: true
    ingress:
      enabled: true
  controllerManager:
    identities:
      clusterSPIFFEIDs:
        default:
          federatesWith:
          - a-org.local
      clusterFederatedTrustDomains:
        a:
          bundleEndpointProfile:
            endpointSPIFFEID: spiffe://a-org.local/spire/server
            type: https_spiffe
          bundleEndpointURL: https://spire-server-federation.a-org.local
          trustDomain: a-org.local

spiffe-oidc-discovery-provider:
  enabled: true
  tls:
    spire:
      enabled: false
  csiDriverName: b.csi.spiffe.io
  ingress:
    enabled: true

spire-agent:
  healthChecks:
    port: 9983
  telemetry:
    prometheus:
      port: 9990
  socketPath: /run/spire/agent-sockets-b/spire-agent.sock

spiffe-csi-driver:
  healthChecks:
    port: 9811
  pluginName: b.csi.spiffe.io
  agentSocketPath: /run/spire/agent-sockets-b/spire-agent.sock

