{{- if and .Values.tags.haAgentCommon .Values.spireIdentityExchange.tls.rest.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spire-nested.identity-exchange-name" . }}-rest
  namespace: {{ include "spire-nested.server-namespace" . }}
  labels:
    {{- include "spire-nested.labels" . | nindent 4 }}
  {{- with .Values.spireIdentityExchange.tls.rest.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.spireIdentityExchange.tls.rest.service.type }}
  {{- if and (eq .Values.spireIdentityExchange.tls.rest.service.type "LoadBalancer") .Values.spireIdentityExchange.tls.rest.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.spireIdentityExchange.tls.rest.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: https
      port: {{ .Values.spireIdentityExchange.tls.rest.service.port }}
      targetPort: rest
      protocol: TCP
  selector:
    {{- toYaml .Values.spireIdentityExchange.podSelector | nindent 4 }}
{{- end }}
