# Default values for spire-lib.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## It is required by CI/CD tools and processes.
## @skip exampleValue
##
exampleValue: spire-lib
