name: Helm Chart CI

on:
  pull_request:
    types: [synchronize, opened, reopened]
    paths-ignore:
      - 'charts/**'
      - '.github/workflows/helm-chart-ci.yaml'
      - '.github/kind/conf/kind-config.yaml'
      - '.github/tests/**/*.yaml'
      - '.github/tests/**/*.sh'
      - '.github/tests/**/*.json'
      - 'examples/**/*.yaml'
      - 'helm-docs.sh'

jobs:
  lint-chart:
    runs-on: ubuntu-22.04
    steps:
      - run: 'echo "Skipping linter"'

  checks:
    runs-on: ubuntu-22.04
    steps:
      - run: 'echo "Skipping checks"'

  test:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        k8s:
          - v1.28.0
          - v1.27.3
          - v1.26.6

    steps:
      - run: 'echo "Skipping tests"'

  build-matrix:
    name: Build matrix
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - id: set-matrix-example
        name: Collect all examples
        run: |
          examples="$(find examples -maxdepth 2 -type f -name run-tests.sh | xargs -I % dirname %)"
          examples_json="$(echo "$examples" | jq -c --slurp --raw-input 'split("\n") | map(select(. != ""))')"
          echo "${examples_json}"
          echo "examples=$examples_json" >>"$GITHUB_OUTPUT"

      - id: set-matrix-integration
        name: Collect all integration tests
        run: |
          integrationtests="$(find tests/integration -maxdepth 2 -type f -name run-tests.sh | xargs -I % dirname %)"
          integrationtests_json="$(echo "$integrationtests" | jq -c --slurp --raw-input 'split("\n") | map(select(. != ""))')"
          echo "${integrationtests_json}"
          echo "integrationtests=$integrationtests_json" >>"$GITHUB_OUTPUT"

    outputs:
      examples: ${{ steps.set-matrix-example.outputs.examples }}
      integrationtests: ${{ steps.set-matrix-integration.outputs.integrationtests }}

  example-test:
    runs-on: ubuntu-22.04

    needs:
      - build-matrix

    strategy:
      matrix:
        k8s:
          - v1.28.0
          - v1.27.3
          - v1.26.6
        example:
          - ${{ fromJson(needs.build-matrix.outputs.examples) }}

    steps:
      - run: 'echo "Skipping example-test"'

  integration-test:
    runs-on: ubuntu-22.04

    needs:
      - build-matrix

    strategy:
      matrix:
        k8s:
          - v1.28.0
          - v1.27.3
          - v1.26.6
        example:
          - ${{ fromJson(needs.build-matrix.outputs.integrationtests) }}

    steps:
      - run: 'echo "Skipping integration-test"'

  upgrade-test:
    runs-on: ubuntu-22.04

    needs:
      - build-matrix

    strategy:
      matrix:
        k8s:
          - v1.28.0
          - v1.27.3
          - v1.26.6

    steps:
      - run: 'echo "Skipping upgrade-test"'
