name: Update devcontainer image

on:
  schedule:
    - cron: '0 8 * * 1'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  HELM_VERSION: v3.11.1

jobs:
  build-and-push-devcontainer-image:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      id-token: write
      packages: write

    env:
      COSIGN_EXPERIMENTAL: 1

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2
        with:
          cosign-release: v2.2.3
      - name: Install regctl
        uses: regclient/actions/regctl-installer@c48159175b58fb90cccd0f98410927a81e04a166 # main
      - name: Log in to GHCR
        uses: docker/login-action@abd2ef45e78c5afb21d64d4ca52ee8550d9572c7 # v4.5.1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build / Push images
        run: |
          set -e
          cd .devcontainer/
          docker build -t ghcr.io/spiffe/helm-charts-hardened-devcontainer:latest .
          docker push ghcr.io/spiffe/helm-charts-hardened-devcontainer:latest
