name: Update devcontainer image

on:
  schedule:
    - cron: '0 8 * * 1'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  HELM_VERSION: v3.11.1

jobs:
  build-and-push-devcontainer-image:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      id-token: write
      packages: write

    env:
      COSIGN_EXPERIMENTAL: 1

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install cosign
        uses: sigstore/cosign-installer@cad07c2e89fa2edd6e2d7bab4c1aa38e53f76003 # v4.1.1
        with:
          cosign-release: v2.2.3
      - name: Install regctl
        uses: regclient/actions/regctl-installer@f3c6d87835906c175eb6ccfc18b348b69bb447e7 # main
      - name: Log in to GHCR
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build / Push images
        run: |
          set -e
          cd .devcontainer/
          docker build -t ghcr.io/spiffe/helm-charts-hardened-devcontainer:latest .
          docker push ghcr.io/spiffe/helm-charts-hardened-devcontainer:latest
